server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: ecom_user
    password: ecom@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: 7653256788j5678900f7687998765432a789023d45672778g576789067g567890678345768
  expiration: 86400000

eureka:
  client:
    enabled: false
